"""Run the independent oracle and the reference parser over every conformance case.

    python tools/oracle/compare.py [--report PATH] [--conformance DIR]

Writes a disagreement report (case id, oracle status, parser status, triage note) and
exits 0 when every disagreement is listed in tools/oracle/triaged.json (and no listed
entry is stale), 1 otherwise.

The reference parser is the system under comparison, so this driver loads it by name
at run time; the recognizer module itself (tools/oracle/recognizer.py) has no import
path to it.  Skeleton strings and the span-free AST shape are compared; the parser
RESOURCE_EXHAUSTED status is reported as "not comparable", never as agreement.
"""
from __future__ import annotations

import argparse
import importlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
DEFAULT_REPORT = str(ROOT / "build" / "oracle" / "disagreements.md")  # build/ is git-ignored

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.oracle.recognizer import recognize  # noqa: E402


def load_cases(directory: Path):
    cases = []
    for path in sorted(directory.glob("*.jsonl")):
        for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if line.strip():
                rec = json.loads(line)
                rec["_file"] = path.name
                cases.append(rec)
    return cases


def _canon(obj) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def compare_case(case, parser_mod, ast_mod):
    """-> (agree: bool, kind: str, oracle_status, parser_status)"""
    surface = case["surface"]
    o = recognize(surface)
    p = parser_mod.parse(surface)
    if p.status == "RESOURCE_EXHAUSTED":
        return False, "not-comparable", o.status, p.status
    if o.status != p.status:
        return False, "status", o.status, p.status
    if o.status == "INVALID":
        return True, "", o.status, p.status
    if sorted(o.skeletons) != sorted(p.skeletons):
        return False, "skeletons", o.status, p.status
    o_shapes = sorted(_canon(s) for s in o.shapes)
    p_shapes = sorted(_canon(ast_mod.shape(a)) for a in p.alternatives)
    if o_shapes != p_shapes:
        return False, "ast-shape", o.status, p.status
    return True, "", o.status, p.status


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--report", default=DEFAULT_REPORT)
    ap.add_argument("--conformance", default=str(ROOT / "conformance"))
    ap.add_argument("--triaged", default=str(HERE / "triaged.json"))
    args = ap.parse_args(argv)

    parser_mod = importlib.import_module("openpona")
    ast_mod = importlib.import_module("openpona.ast")
    cases = load_cases(Path(args.conformance))
    triaged = json.loads(Path(args.triaged).read_text(encoding="utf-8"))
    observations = triaged.get("_observations", [])
    triaged = {k: v for k, v in triaged.items() if not k.startswith("_")}

    rows, agree = [], 0
    for case in cases:
        ok, kind, o_status, p_status = compare_case(case, parser_mod, ast_mod)
        if ok:
            agree += 1
        else:
            rows.append((case, kind, o_status, p_status))

    untriaged = [r for r in rows if r[0]["id"] not in triaged]
    disagreeing = {r[0]["id"] for r in rows}
    stale = sorted(set(triaged) - disagreeing)
    unknown = sorted(set(triaged) - {c["id"] for c in cases})

    lines = [
        "# N4 oracle vs parser disagreement report",
        "",
        "Generated by `tools/oracle/compare.py` (independent recognizer in "
        "`tools/oracle/recognizer.py`, written from SPEC 5-7 and canon/ only).",
        "",
        f"- cases compared: {len(cases)} (every record of conformance/*.jsonl)",
        f"- agree (status, skeleton set and span-free AST shape): {agree}",
        f"- disagree: {len(rows)}; triaged in tools/oracle/triaged.json: "
        f"{len(rows) - len(untriaged)}; NOT triaged: {len(untriaged)}",
        f"- stale triage entries (listed but no longer disagreeing): {stale or 'none'}",
        f"- triage entries naming no case: {unknown or 'none'}",
        "",
        "| case id | surface | expected | oracle status | parser status | kind | triage note |",
        "|---|---|---|---|---|---|---|",
    ]
    for case, kind, o_status, p_status in rows:
        t = triaged.get(case["id"])
        note = (f"[{t['class']}] {t['note']}" if t else "UNTRIAGED")
        surface = case["surface"].replace("|", "\\|") or "(empty)"
        lines.append(f"| {case['id']} | `{surface}` | {case['expect_status']} | {o_status} | "
                     f"{p_status} | {kind} | {note} |")
    if not rows:
        lines.append("| (none) | | | | | | |")
    if observations:
        lines += ["", "## Observations outside the corpus (not conformance cases)", ""]
        lines += [f"- {o}" for o in observations]
    Path(args.report).parent.mkdir(parents=True, exist_ok=True)
    Path(args.report).write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"compared {len(cases)} cases: {agree} agree, {len(rows)} disagree, "
          f"{len(untriaged)} untriaged, stale={stale}, unknown={unknown}")
    print(f"report: {args.report}")
    for case, kind, o_status, p_status in untriaged:
        print(f"UNTRIAGED {case['id']} ({kind}): oracle {o_status} parser {p_status}")
    return 0 if not untriaged and not stale and not unknown else 1


if __name__ == "__main__":
    raise SystemExit(main())
