"""Binding validator for persisted OpenPona records (TP-03).

ENGINEERING module.  It checks a persisted record against its declared profile
(`schema/profiles/*.schema.json`, generated by `openpona.record_schemas`) and then
against everything JSON Schema cannot see:

1. the surface is re-parsed with the reference parser and the record's `tokens` and
   `parse_reference` (status, alternative index, AST digest) must match the result;
2. `subject` / `object` / `context` / `predicate` token lists must match the nodes of
   the parsed AST in that role (typed mismatch, never trusted from the sidecar);
3. entity bindings must be consistent (no bound ambiguous address, no unbound
   "resolved" address, no two different `bound_ref` for one address);
4. the binding seal (sha256 over statement_id, surface, parse pin, resolution context,
   entity bindings and source revision) must match, so a persisted binding cannot be edited
   in place; `check_immutable` compares a persisted record with a later version.

It never decides truth and never grants permission (CHANGE_GATES 4, 5): a record that
is valid here is well-formed and consistently bound, nothing more.  The result is a
list of typed `Issue` codes; see docs/record-profiles.md for the table.
"""
from __future__ import annotations

from dataclasses import dataclass
import copy
import hashlib
import json
from pathlib import Path
import re

from . import PARSER_API_VERSION, ast, parse
from . import _schemacheck
from .record_schemas import (
    ENTITY_ROLES, EXPRESSION_ROLES, PROFILES, REF_PATTERN, SCHEMA_VERSION,
    TOKEN_VERSION, X_PATTERN, build_schema,
)

__all__ = [
    "Issue", "ValidationResult", "validate_record", "validate_file", "check_immutable",
    "parse_reference_for", "ast_digest", "ast_roles", "binding_digest", "seal_record",
    "migrate_legacy", "MigrationError", "load_schema", "AUTHORIZATION_MESSAGE", "ISSUE_CODES",
]

AUTHORIZATION_MESSAGE = (
    "authorization is not a record field and cannot be derived from truth_status: a "
    "statement never grants permission (CHANGE_GATES 4); identity, authority, policy and "
    "preconditions are enforced by the runtime outside the language")
_AUTH_EXACT = {"authorized", "authorised", "authorization", "authorisation", "permitted",
               "permission", "permissions", "approved", "approval", "granted", "allowed",
               "may_execute", "can_execute", "execute", "executable"}
_REF = re.compile(REF_PATTERN)
_X = re.compile(X_PATTERN)


# --------------------------------------------------------------------- results
ISSUE_CODES = frozenset({
    # input
    "unreadable_file", "invalid_json", "not_an_object", "missing_profile",
    "unknown_profile", "profile_mismatch",
    # structure and schema
    "authorization_from_truth_status", "missing_required_field", "unknown_key",
    "non_canonical_token", "token_version_mismatch", "schema_version_unsupported",
    "wrong_type", "bad_format", "bad_timestamp", "invalid_value", "constraint_violation",
    "observed_without_evidence", "provenance_source_missing", "binding_rule_violation",
    # parser cross-check
    "surface_tokens_mismatch", "surface_parse_invalid", "surface_parse_unavailable",
    "parse_api_incompatible", "parse_reference_mismatch",
    # AST roles
    "ast_subject_mismatch", "ast_object_mismatch", "ast_context_mismatch",
    "ast_predicate_mismatch", "missing_binding",
    # entity binding and seal
    "unbound_ambiguous_address", "missing_bound_ref", "ambiguous_address_bound",
    "conflicting_bound_ref", "resolution_status_mismatch", "binding_seal_mismatch",
    # immutability
    "statement_id_mismatch", "bound_ref_rewritten", "resolution_context_rewritten",
    "binding_seal_rewritten", "persisted_record_modified",
})


@dataclass(frozen=True)
class Issue:
    """One typed finding.  `code` is stable API; `message` is for humans."""
    code: str
    path: str
    message: str

    def __post_init__(self):
        if self.code not in ISSUE_CODES:
            raise ValueError(f"unregistered issue code {self.code!r}")

    def __str__(self) -> str:
        return f"{self.code}: {self.path or '$'}: {self.message}"


@dataclass(frozen=True)
class ValidationResult:
    valid: bool
    profile: str | None
    issues: tuple

    @property
    def reason(self) -> str | None:
        """The first (primary) typed reason, or None when valid."""
        return self.issues[0].code if self.issues else None


_SCHEMAS: dict[str, dict] = {}


def load_schema(profile: str) -> dict:
    """The profile schema.  Built from `openpona.record_schemas` (same bytes as the
    committed `schema/profiles/*.json`; a test enforces that)."""
    if profile not in _SCHEMAS:
        _SCHEMAS[profile] = build_schema(profile)
    return _SCHEMAS[profile]


# ------------------------------------------------------------------ canonical hashes
def _canonical(obj) -> bytes:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"),
                      ensure_ascii=False).encode("utf-8")


def ast_digest(alternative) -> str:
    """sha256 of the canonical JSON (with spans) of one parse alternative."""
    return hashlib.sha256(ast.to_canonical_json(alternative).encode("utf-8")).hexdigest()


def parse_reference_for(surface: str, alternative_index: int = 0) -> dict:
    """The `parse_reference` pin for `surface` under the CURRENT reference parser."""
    res = parse(surface)
    if res.status not in ("RESOLVED", "AMBIGUOUS"):
        raise ValueError(f"cannot pin a parse of status {res.status}: {surface!r}")
    if not 0 <= alternative_index < len(res.alternatives):
        raise ValueError(f"alternative_index {alternative_index} out of range "
                         f"(0..{len(res.alternatives) - 1})")
    return {"api_version": res.api_version, "status": res.status,
            "alternative_index": alternative_index,
            "ast_sha256": ast_digest(res.alternatives[alternative_index])}


def _sealed_payload(record: dict) -> dict:
    """What the binding seal covers: the statement_id (when present), the surface and
    its parse pin, the resolution context, every entity binding and the source revision.  Not covered: truth status,
    actor, evidence, literals and `x-` extensions (they are not part of the binding)."""
    return {
        "statement_id": record.get("statement_id"),
        "token_version": record.get("token_version"),
        "surface": record.get("surface"),
        "parse_reference": _strip_x(record.get("parse_reference")),
        "resolution_status": record.get("resolution_status"),
        "resolution_context": record.get("resolution_context"),
        "entities": {r: _strip_x(record[r]) for r in EXPRESSION_ROLES if r in record},
        "source_revision": (record.get("binding_seal") or {}).get("source_revision"),
    }


def binding_digest(record: dict) -> str:
    """sha256 hex of the sealed payload (see `_sealed_payload`)."""
    return hashlib.sha256(_canonical(_sealed_payload(record))).hexdigest()


def seal_record(record: dict, source_revision: str) -> dict:
    """Return a copy of `record` with `binding_seal` computed for `source_revision`
    (the revision of the graph / ontology the addresses were resolved against)."""
    out = copy.deepcopy(record)
    out["binding_seal"] = {"algorithm": "sha256", "source_revision": source_revision,
                           "digest": ""}
    out["binding_seal"]["digest"] = binding_digest(out)
    return out


def _strip_x(obj):
    """Deep copy without `x-` extension keys."""
    if isinstance(obj, dict):
        return {k: _strip_x(v) for k, v in obj.items() if not _X.match(k)}
    if isinstance(obj, list):
        return [_strip_x(v) for v in obj]
    return obj


# ----------------------------------------------------------------------- AST roles
def ast_roles(alternative) -> dict:
    """The token lists of the roles a record may bind, read from a parse alternative.

    `context`   tokens before a (non-source) `la`, or None
    `subject`   tokens of the subject of a predication, or None
    `objects`   token lists of every `e` item of every predicate
    `predicates` token lists of every predicate head (source predicates have none)
    """
    node = alternative
    context = None
    if isinstance(node, ast.Context):
        if not node.source:
            context = ast.to_tokens(node.context)
        node = node.body
    subject, objects, predicates = None, [], []
    if isinstance(node, ast.Predication):
        subject = ast.to_tokens(node.subject)
        for p in node.predicates:
            if p.head is not None:
                predicates.append(ast.to_tokens(p.head))
            if p.objects is not None:
                objects.extend(ast.to_tokens(i) for i in p.objects.items)
    return {"context": context, "subject": subject, "objects": objects,
            "predicates": predicates}


# ------------------------------------------------------------- authorization scan
def _auth_key(key: str) -> bool:
    k = key.lower()
    if k.startswith("x-"):
        k = k[2:]
    k = k.replace("-", "_")
    return k in _AUTH_EXACT or "authoriz" in k or "authoris" in k


def _authorization_issues(obj, path: str = "") -> list[Issue]:
    """Keys that look like an authorization decision, anywhere in the record's structure
    (not inside `literals`, whose keys are free data, and not inside `x-` values).
    A key-name heuristic: it catches the obvious derivation, it does not prove absence."""
    out: list[Issue] = []
    if isinstance(obj, dict):
        for key, value in obj.items():
            here = f"{path}/{key}"
            if _auth_key(key):
                out.append(Issue("authorization_from_truth_status", here,
                                 AUTHORIZATION_MESSAGE))
            elif key != "literals" and not _X.match(key):
                out.extend(_authorization_issues(value, here))
    elif isinstance(obj, list):
        for i, value in enumerate(obj):
            out.extend(_authorization_issues(value, f"{path}/{i}"))
    return out


# ------------------------------------------------------------- schema issue typing
def _type_schema_issue(i: _schemacheck.SchemaIssue) -> Issue:
    kw, path = i.keyword, i.path
    if kw == "required":
        return Issue("missing_required_field", f"{path}/{i.detail}", i.message)
    if kw == "additionalProperties":
        return Issue("unknown_key", path,
                     f"{i.message}; only documented keys and `x-` extension keys are allowed")
    if kw == "enum" and re.search(r"/tokens/[0-9]+$", path):
        return Issue("non_canonical_token", path,
                     f"{i.message}; the language has exactly the 42 tokens of anu 1.1")
    if kw == "const":
        code = {"/token_version": "token_version_mismatch",
                "/schema_version": "schema_version_unsupported",
                "/profile": "profile_mismatch"}.get(path, "invalid_value")
        return Issue(code, path, i.message)
    if kw == "type":
        return Issue("wrong_type", path, i.message)
    if kw in ("format", "pattern"):
        return Issue("bad_timestamp" if path.endswith("created_at") else "bad_format",
                     path, i.message)
    if kw == "enum":
        return Issue("invalid_value", path, i.message)
    return Issue("constraint_violation", path, f"{kw}: {i.message}")


def _type_conditional_issue(i: _schemacheck.SchemaIssue) -> Issue:
    path = i.path + (f"/{i.detail}" if i.keyword == "required" else "")
    if "evidence_refs" in path:
        return Issue("observed_without_evidence", "/evidence_refs",
                     "truth_status 'observed' requires at least one evidence_refs entry "
                     "(a statement is not evidence; CHANGE_GATES 5)")
    if path.endswith("/source_event"):
        return Issue("provenance_source_missing", path,
                     "provenance.kind 'source_event' requires source_event")
    return Issue("binding_rule_violation", path, f"{i.keyword}: {i.message}")


# ---------------------------------------------------------------- semantic checks
def _parse_issues(record: dict):
    """Surface / tokens / parse_reference checks.  Returns (issues, alternative|None)."""
    tokens, surface = record["tokens"], record["surface"]
    if surface != " ".join(tokens):
        return [Issue("surface_tokens_mismatch", "/tokens",
                      "tokens must equal the surface split on single spaces")], None
    res = parse(surface)
    if res.status == "INVALID":
        return [Issue("surface_parse_invalid", "/surface",
                      f"the reference parser rejects the surface: {'; '.join(res.errors)}")], None
    if res.status not in ("RESOLVED", "AMBIGUOUS"):
        return [Issue("surface_parse_unavailable", "/surface",
                      f"no parse verdict (status {res.status}); a record cannot pin it")], None
    pin = record["parse_reference"]
    if pin["api_version"].split(".")[0] != PARSER_API_VERSION.split(".")[0]:
        return [Issue("parse_api_incompatible", "/parse_reference/api_version",
                      f"record pins parser API {pin['api_version']}, this parser is "
                      f"{PARSER_API_VERSION}; migrate the record "
                      f"(docs/record-migration.md)")], None
    if pin["status"] != res.status:
        return [Issue("parse_reference_mismatch", "/parse_reference/status",
                      f"record says {pin['status']}, the parser says {res.status}")], None
    if pin["alternative_index"] >= len(res.alternatives):
        return [Issue("parse_reference_mismatch", "/parse_reference/alternative_index",
                      f"index {pin['alternative_index']} but the parse has "
                      f"{len(res.alternatives)} alternative(s)")], None
    alt = res.alternatives[pin["alternative_index"]]
    if ast_digest(alt) != pin["ast_sha256"]:
        return [Issue("parse_reference_mismatch", "/parse_reference/ast_sha256",
                      "the pinned AST digest differs from the parse of this surface "
                      "under the current parser")], None
    return [], alt


def _semantic(record: dict) -> list[Issue]:
    out, alt = _parse_issues(record)
    if alt is not None:
        out.extend(_role_issues(record, ast_roles(alt)))
    out.extend(_entity_issues(record))
    if "binding_seal" in record and record["binding_seal"]["digest"] != binding_digest(record):
        out.append(Issue("binding_seal_mismatch", "/binding_seal/digest",
                         "the sealed binding (surface, parse pin, resolution_context, "
                         "entities, source_revision) was changed after sealing, or the "
                         "seal was never computed; a persisted binding must not be edited "
                         "in place - write a new record that supersedes it"))
    return out


def _role_issues(record: dict, roles: dict) -> list[Issue]:
    out: list[Issue] = []
    for role, label in (("subject", "ast_subject_mismatch"), ("context", "ast_context_mismatch")):
        want = roles[role]
        have = record.get(role, {}).get("tokens") if role in record else None
        if have is None:
            if want is not None:
                out.append(Issue("missing_binding", f"/{role}",
                                 f"the AST has a {role} ({' '.join(want)}) but the record "
                                 f"binds none; bind it or mark it AMBIGUOUS / UNRESOLVED"))
        elif have != want:
            out.append(Issue(label, f"/{role}/tokens",
                             f"record {role} is [{' '.join(have)}], the parsed AST has "
                             f"{'[' + ' '.join(want) + ']' if want is not None else 'no ' + role}"))
    if "object" in record and record["object"]["tokens"] not in roles["objects"]:
        shown = " | ".join("[" + " ".join(o) + "]" for o in roles["objects"]) or "no object"
        out.append(Issue("ast_object_mismatch", "/object/tokens",
                         f"record object is [{' '.join(record['object']['tokens'])}], the "
                         f"parsed AST has {shown}"))
    if "predicate" in record and record["predicate"]["tokens"] not in roles["predicates"]:
        shown = " | ".join("[" + " ".join(o) + "]" for o in roles["predicates"]) or "no predicate"
        out.append(Issue("ast_predicate_mismatch", "/predicate/tokens",
                         f"record predicate is [{' '.join(record['predicate']['tokens'])}], "
                         f"the parsed AST has {shown}"))
    return out


def _entity_issues(record: dict) -> list[Issue]:
    out: list[Issue] = []
    seen: dict[tuple, tuple[str, str]] = {}
    statuses = []
    for role in ENTITY_ROLES:
        ent = record.get(role)
        if ent is None:
            continue
        status, ref, cands = ent["resolution_status"], ent.get("bound_ref"), ent.get("candidates", [])
        statuses.append((role, status))
        where = f"/{role}"
        if status == "RESOLVED":
            if ref is None and len(cands) >= 2:
                out.append(Issue("unbound_ambiguous_address", where,
                                 f"{role} is marked RESOLVED but has {len(cands)} candidates "
                                 f"and no bound_ref: an ambiguous address must stay AMBIGUOUS"))
            elif ref is None:
                out.append(Issue("missing_bound_ref", where,
                                 f"{role} is marked RESOLVED but has no bound_ref"))
            elif cands and cands != [ref]:
                out.append(Issue("conflicting_bound_ref", where,
                                 f"bound_ref {ref} conflicts with candidates {cands}: a "
                                 f"binding chosen among competitors is a guess"))
        elif status == "AMBIGUOUS" and ref is not None:
            out.append(Issue("ambiguous_address_bound", where,
                             f"{role} is AMBIGUOUS yet carries bound_ref {ref}: never pick "
                             f"one candidate (canon/05 'no probabilistic guess')"))
        key = tuple(ent["tokens"])
        if ref is not None and status == "RESOLVED":
            if key in seen and seen[key][1] != ref:
                out.append(Issue("conflicting_bound_ref", where,
                                 f"address [{' '.join(key)}] is bound to {ref} here but to "
                                 f"{seen[key][1]} at /{seen[key][0]}; in one resolution "
                                 f"context an address resolves to exactly one reference"))
            seen.setdefault(key, (role, ref))
    # statement-level status must be the aggregate of the entity statuses
    kinds = {s for _, s in statuses}
    agg = "AMBIGUOUS" if "AMBIGUOUS" in kinds else "UNRESOLVED" if "UNRESOLVED" in kinds else "RESOLVED"
    have = record["resolution_status"]
    if have != agg:
        if have == "RESOLVED" and agg == "AMBIGUOUS":
            role = next(r for r, s in statuses if s == "AMBIGUOUS")
            out.append(Issue("unbound_ambiguous_address", f"/{role}",
                             f"the statement claims RESOLVED but {role} is AMBIGUOUS"))
        else:
            out.append(Issue("resolution_status_mismatch", "/resolution_status",
                             f"statement says {have} but its entities aggregate to {agg} "
                             f"(AMBIGUOUS beats UNRESOLVED beats RESOLVED)"))
    return out


# --------------------------------------------------------------------- entry points
def validate_record(record, profile: str | None = None) -> ValidationResult:
    """Validate one record (already parsed JSON).  `profile` overrides nothing: if given
    it must equal the record's own `profile` field."""
    if not isinstance(record, dict):
        return _result(None, [Issue("not_an_object", "", "a record is a JSON object")])
    declared = record.get("profile")
    if declared is None:
        return _result(None, [Issue("missing_profile", "/profile",
                                    f"declare one of {', '.join(PROFILES)}")])
    if declared not in PROFILES:
        return _result(None, [Issue("unknown_profile", "/profile",
                                    f"{declared!r} is not one of {', '.join(PROFILES)}")])
    if profile is not None and profile != declared:
        return _result(declared, [Issue("profile_mismatch", "/profile",
                                        f"expected {profile}, the record declares {declared}")])
    auth = _authorization_issues(record)
    auth_paths = {i.path for i in auth}
    found = _schemacheck.check(load_schema(declared), record)
    hard = [i for i in found if not i.conditional
            and not (i.keyword == "additionalProperties" and i.path in auth_paths)]
    issues = list(auth) + [_type_schema_issue(i) for i in hard]
    if hard:
        return _result(declared, issues)
    sem = _semantic(record) if declared != "ParsedStatement" else _semantic_parsed(record)
    issues += sem
    covered = {i.path for i in sem}
    for i in found:
        if i.conditional:
            typed = _type_conditional_issue(i)
            if not any(typed.path == p or typed.path.startswith(p + "/") or
                       p.startswith(typed.path + "/") for p in covered):
                issues.append(typed)
    return _result(declared, issues)


def _semantic_parsed(record: dict) -> list[Issue]:
    """ParsedStatement: surface, tokens and parse pin only (no bindings, no seal)."""
    return _parse_issues(record)[0]


def _result(profile, issues) -> ValidationResult:
    return ValidationResult(not issues, profile, tuple(issues))


def validate_file(path) -> ValidationResult:
    """Read and validate a JSON file; unreadable / malformed input is a typed issue."""
    p = Path(path)
    try:
        text = p.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        return _result(None, [Issue("unreadable_file", str(p), str(e))])
    try:
        record = json.loads(text)
    except json.JSONDecodeError as e:
        return _result(None, [Issue("invalid_json", "", f"{e.msg} (line {e.lineno}, col {e.colno})")])
    return validate_record(record)


# --------------------------------------------------------------------- immutability
def check_immutable(persisted: dict, candidate: dict) -> list[Issue]:
    """Compare a persisted record with a later version carrying the same statement_id.

    A persisted binding is write-once.  Any difference outside `x-` extension keys is
    reported with the most specific typed code; the only sanctioned way to change what a
    statement refers to is a NEW record (new statement_id, `supersedes` = old id) while
    the old one stays as written.  Returns [] when nothing sealed changed."""
    if persisted.get("statement_id") != candidate.get("statement_id") or \
            persisted.get("statement_id") is None:
        return [Issue("statement_id_mismatch", "/statement_id",
                      "immutability is checked between versions of the same statement_id")]
    a, b = _strip_x(persisted), _strip_x(candidate)
    if a == b:
        return []
    out: list[Issue] = []
    for role in EXPRESSION_ROLES:
        ra, rb = a.get(role, {}), b.get(role, {})
        if ra.get("bound_ref") != rb.get("bound_ref") or ra.get("candidates") != rb.get("candidates"):
            out.append(Issue("bound_ref_rewritten", f"/{role}",
                             f"{role} binding changed from {ra.get('bound_ref')!r} to "
                             f"{rb.get('bound_ref')!r}; history is immutable"))
    if a.get("resolution_context") != b.get("resolution_context"):
        out.append(Issue("resolution_context_rewritten", "/resolution_context",
                         "the resolution context of a persisted binding was changed; a "
                         "later context may resolve the address differently NOW but must "
                         "not change what the historical statement referred to"))
    if a.get("binding_seal") != b.get("binding_seal"):
        out.append(Issue("binding_seal_rewritten", "/binding_seal",
                         "the binding seal of a persisted record was replaced"))
    if not out:
        keys = sorted(k for k in set(a) | set(b) if a.get(k) != b.get(k))
        out.append(Issue("persisted_record_modified", "/" + keys[0],
                         f"persisted record changed in: {', '.join(keys)}"))
    return out


# ------------------------------------------------------------------ legacy migration
class MigrationError(ValueError):
    """A legacy record cannot be migrated without inventing information."""


_LEGACY_ROLE_KEYS = ("subject", "predicate", "object", "context")


def migrate_legacy(legacy: dict, *, source_revision: str,
                   alternative_index: int | None = None) -> dict:
    """Convert a record in the legacy `schema/statement.schema.json` shape (or the
    `docs/for-agents.md` section 6 template) to the new profiles.

    Never invents: a legacy `observed` without evidence, an unparsable surface or an
    ambiguous parse without an explicit `alternative_index` raises `MigrationError`.
    Unmapped legacy fields are preserved under `x-legacy`; unknown information is
    recorded under `x-migration`.  Result profile: AgentEvent when statement_id,
    created_at (RFC 3339), actor, truth_status and a resolution context are all present,
    else BoundStatement.  The result is validated before it is returned."""
    problems: list[str] = []
    surface = legacy.get("surface")
    if not isinstance(surface, str) or not surface:
        raise MigrationError("legacy record has no surface")
    res = parse(surface)
    if res.status not in ("RESOLVED", "AMBIGUOUS"):
        raise MigrationError(f"legacy surface does not parse ({res.status}): {surface!r}")
    if res.status == "AMBIGUOUS" and alternative_index is None:
        raise MigrationError("legacy surface has an ambiguous parse; pass alternative_index "
                             "explicitly (the legacy record cannot say which reading was meant)")
    legacy_x: dict = {}
    migration: dict = {}
    rec: dict = {
        "schema_version": SCHEMA_VERSION, "token_version": TOKEN_VERSION,
        "surface": " ".join(res.tokens), "tokens": list(res.tokens),
        "parse_reference": parse_reference_for(surface, alternative_index or 0),
    }
    if legacy.get("token_version") not in (None, TOKEN_VERSION):
        raise MigrationError(f"legacy token_version {legacy['token_version']!r} is not {TOKEN_VERSION}")
    statuses = []
    for role in _LEGACY_ROLE_KEYS:
        ex = legacy.get(role)
        if ex is None:
            continue
        if role == "predicate":
            rec[role] = {"tokens": list(ex["tokens"])}
            continue
        ref, cands = ex.get("bound_ref"), list(ex.get("candidates") or [])
        status = "RESOLVED" if ref else "AMBIGUOUS" if len(cands) >= 2 else "UNRESOLVED"
        ent = {"tokens": list(ex["tokens"]), "resolution_status": status}
        if ref:
            ent["bound_ref"] = ref
        if cands:
            ent["candidates"] = cands
        extras = {k: v for k, v in ex.items() if k not in ("tokens", "bound_ref", "candidates")}
        if extras:
            legacy_x[role] = extras
        rec[role] = ent
        statuses.append(status)
    rec["resolution_status"] = ("AMBIGUOUS" if "AMBIGUOUS" in statuses else
                                "UNRESOLVED" if "UNRESOLVED" in statuses else "RESOLVED")
    ctx = legacy.get("resolution_context") or legacy.get("context_refs") or []
    rec["resolution_context"] = list(ctx)
    if not ctx:
        migration["resolution_context"] = "unknown in the legacy record"
    for key in ("statement_id", "actor", "truth_status", "created_at", "literals", "cause_refs"):
        if legacy.get(key) is not None:
            rec[key] = legacy[key]
    ev = legacy.get("evidence_refs", legacy.get("evidence"))
    if ev:
        rec["evidence_refs"] = list(ev)
    elif legacy.get("truth_status") == "observed":
        problems.append("legacy 'observed' record has no evidence; refusing to carry an "
                        "unevidenced observation over (CHANGE_GATES 5) - supply evidence "
                        "or re-status it")
    for key in ("parse_status", "tokens", "branch", "context_refs", "source_event",
                "evidence", "resolution_status", "candidates", "token_version"):
        if key in legacy and legacy[key] is not None:
            legacy_x[key] = legacy[key]
    if problems:
        raise MigrationError("; ".join(problems))
    full = all(k in rec for k in ("statement_id", "created_at", "actor", "truth_status")) \
        and bool(ctx)
    prov = {"kind": "legacy_migration"}
    if legacy.get("source_event"):
        prov["source_event"] = legacy["source_event"]
    if full:
        rec["profile"] = "AgentEvent"
        rec["provenance"] = prov
    else:
        rec["profile"] = "BoundStatement"
        migration["missing_for_agent_event"] = [
            k for k in ("statement_id", "created_at", "actor", "truth_status")
            if k not in rec] + ([] if ctx else ["resolution_context"])
        rec["provenance"] = prov
    if legacy_x:
        rec["x-legacy"] = legacy_x
    if migration:
        rec["x-migration"] = migration
    out = seal_record(rec, source_revision)
    result = validate_record(out)
    if not result.valid:
        raise MigrationError("migrated record is not valid: " +
                             "; ".join(str(i) for i in result.issues))
    return out
